volumes:
  postgres_data:
    driver: local  # This uses the local storage driver
  redis-data:
    driver: local

services:
  app:
    image: docker.vocr.vn/dori_app:latest
    container_name: app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/app/dist
      - ./cert/:/cert
    depends_on:
      - api
  api:
    image: docker.vocr.vn/dori_api:latest
    container_name: api
    env_file: ${ENV_FILE}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
      - celery
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    shm_size: 64mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a6suzyh2V1jKrYX
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_DB: dori
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis: # for celery
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  celery:
    image: docker.vocr.vn/celery:latest
    container_name: "celery"
    command: celery -A tasks worker --loglevel=info --concurrency=1 --max-tasks-per-child=10
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped
