volumes:
  postgres_data:
    driver: local  # This uses the local storage driver
  redis-data:
    driver: local

services:
  app:
    image: docker.vocr.vn/dori_app:latest
    container_name: app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/app/dist
      - ./cert/:/cert
    depends_on:
      - api
  api:
    image: docker.vocr.vn/dori_api:latest
    container_name: api
    env_file: ${ENV_FILE}
    ports:
      - "8000:8000"
    volumes:
      - ./uploaded_files/:/app/uploaded_files/
    restart: unless-stopped
    depends_on:
      - db
      - celery
  landing_page:
    image: docker.vocr.vn/dori_landing_page:latest
    container_name: landing_page
    ports:
      - 3000:3000
    restart: unless-stopped
  landing_page_backend:
    image: docker.vocr.vn/landing_page_backend:latest
    container_name: landing_page_backend
    ports:
      - 8003:8000
    restart: unless-stopped
  db:
    image: postgres
    container_name: postgres
    env_file: ${ENV_FILE}
    ports:
      - 5432:5432
    restart: unless-stopped
    shm_size: 64mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a6suzyh2V1jKrYX
      POSTGRES_DB: dori
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis: # for celery
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  celery:
    image: docker.vocr.vn/celery:latest
    container_name: "celery"
    command: celery -A tasks worker --loglevel=info --concurrency=1 --max-tasks-per-child=10
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    restart: unless-stopped
